name: Sync fork with upstream

on:
  schedule:
  - cron:  "0 0 1/7 * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.SYNC_PAT }}
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/we-kode/mml.app"
        source_branch: "master"
        destination_branch: "master"
        github_token: ${{ secrets.SYNC_PAT }}
        sync_tags: "true"
    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag
    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag-semver
      with:
        semver_only: true
        initial_version: '0.0.0'
    - uses: actions-ecosystem/action-push-tag@v1
      if: ${{ !endsWith( steps.get-latest-tag.outputs.tag, '-ecg' ) &&  steps.get-latest-tag-semver.outputs.tag != '0.0.0'}}
      with:
        tag: ${{ steps.get-latest-tag-semver.outputs.tag }}-ecg
    
    - name: create release
      uses: ncipollo/release-action@v1
      if: ${{ !endsWith( steps.get-latest-tag.outputs.tag, '-ecg' ) &&  steps.get-latest-tag-semver.outputs.tag != '0.0.0'}}
      with:
        tag: ${{ steps.get-latest-tag-semver.outputs.tag }}-ecg
        token: ${{ secrets.SYNC_PAT }}
